package com.ffp.data;
// Generated Aug 4, 2017 3:27:06 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Demand generated by hbm2java
 */
@Entity
@Table(name = "contact_us", catalog = "crm")
public class Contactus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	
	private String name;
	private String email;
	private String phone;
	private String desc;
	

	public Contactus() {
	}

	public Contactus(String name, String email,String phone,
			String desc) {
		
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.desc = desc;
		
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	
	public void setId(Integer id) {
		this.id = id;
	}

	

	@Column(name = "USERNAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "EMAIL", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHONE", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "DESCR", length = 1000)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	
}
