package com.ffp.data;
// Generated Aug 4, 2017 3:27:06 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Demand generated by hbm2java
 */
@Entity
@Table(name = "demand", catalog = "crm")
public class Demand implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String product;
	private String variety;
	private String price;
	private String quantity;
	private String measurement;
	private String country;
	private String city;

	public Demand() {
	}

	public Demand(String product, String variety, String price, String quantity, String measurement, String country,
			String city) {
		this.product = product;
		this.variety = variety;
		this.price = price;
		this.quantity = quantity;
		this.measurement = measurement;
		this.country = country;
		this.city = city;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PRODUCT", nullable = false, length = 45)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "VARIETY", nullable = false, length = 45)
	public String getVariety() {
		return this.variety;
	}

	public void setVariety(String variety) {
		this.variety = variety;
	}

	@Column(name = "PRICE", nullable = false, length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "QUANTITY", nullable = false, length = 45)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	@Column(name = "MEASUREMENT", nullable = false, length = 45)
	public String getMeasurement() {
		return this.measurement;
	}

	public void setMeasurement(String measurement) {
		this.measurement = measurement;
	}

	@Column(name = "COUNTRY", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "CITY", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
