package com.ffp.data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InboxOutbox generated by hbm2java
 */
@Entity
@Table(name = "inbox_outbox", catalog = "crm")
public class InboxOutbox implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Negotiation negotiation;
	private UserProfile userProfileBySentBy;
	private UserProfile userProfileByRecievedBy;
	private String price;
	private String quantity;
	private String body;
	private String udf1;
	private String udf2;

	public InboxOutbox() {
	}

	public InboxOutbox(Negotiation negotiation, UserProfile userProfileBySentBy, UserProfile userProfileByRecievedBy,
			String price, String quantity, String body) {
		this.negotiation = negotiation;
		this.userProfileBySentBy = userProfileBySentBy;
		this.userProfileByRecievedBy = userProfileByRecievedBy;
		this.price = price;
		this.quantity = quantity;
		this.body = body;
	}

	public InboxOutbox(Negotiation negotiation, UserProfile userProfileBySentBy, UserProfile userProfileByRecievedBy,
			String price, String quantity, String body, String udf1, String udf2) {
		this.negotiation = negotiation;
		this.userProfileBySentBy = userProfileBySentBy;
		this.userProfileByRecievedBy = userProfileByRecievedBy;
		this.price = price;
		this.quantity = quantity;
		this.body = body;
		this.udf1 = udf1;
		this.udf2 = udf2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "NEG_ID", nullable = false)
	public Negotiation getNegotiation() {
		return this.negotiation;
	}

	public void setNegotiation(Negotiation negotiation) {
		this.negotiation = negotiation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SENT_BY", nullable = false)
	public UserProfile getUserProfileBySentBy() {
		return this.userProfileBySentBy;
	}

	public void setUserProfileBySentBy(UserProfile userProfileBySentBy) {
		this.userProfileBySentBy = userProfileBySentBy;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "RECIEVED_BY", nullable = false)
	public UserProfile getUserProfileByRecievedBy() {
		return this.userProfileByRecievedBy;
	}

	public void setUserProfileByRecievedBy(UserProfile userProfileByRecievedBy) {
		this.userProfileByRecievedBy = userProfileByRecievedBy;
	}

	@Column(name = "PRICE", nullable = false, length = 45)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "QUANTITY", nullable = false, length = 45)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	@Column(name = "BODY", nullable = false, length = 500)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "UDF_1", length = 45)
	public String getUdf1() {
		return this.udf1;
	}

	public void setUdf1(String udf1) {
		this.udf1 = udf1;
	}

	@Column(name = "UDF_2", length = 45)
	public String getUdf2() {
		return this.udf2;
	}

	public void setUdf2(String udf2) {
		this.udf2 = udf2;
	}

}