package com.ffp.data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Negotiation generated by hbm2java
 */
@Entity
@Table(name = "negotiation", catalog = "crm")
public class Negotiation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private UserProfile userProfileByBuyerId;
	private UserProfile userProfileBySellerId;
	private String status;
	private String comment;
//	private Set inboxOutboxes = new HashSet(0);

	public Negotiation() {
	}

	public Negotiation(UserProfile userProfileByBuyerId, UserProfile userProfileBySellerId, String status) {
		this.userProfileByBuyerId = userProfileByBuyerId;
		this.userProfileBySellerId = userProfileBySellerId;
		this.status = status;
	}

	public Negotiation(UserProfile userProfileByBuyerId, UserProfile userProfileBySellerId, String status,
			String comment) {
//	, Set inboxOutboxes) {
		this.userProfileByBuyerId = userProfileByBuyerId;
		this.userProfileBySellerId = userProfileBySellerId;
		this.status = status;
		this.comment = comment;
//		this.inboxOutboxes = inboxOutboxes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "BUYER_ID", nullable = false)
	public UserProfile getUserProfileByBuyerId() {
		return this.userProfileByBuyerId;
	}

	public void setUserProfileByBuyerId(UserProfile userProfileByBuyerId) {
		this.userProfileByBuyerId = userProfileByBuyerId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SELLER_ID", nullable = false)
	public UserProfile getUserProfileBySellerId() {
		return this.userProfileBySellerId;
	}

	public void setUserProfileBySellerId(UserProfile userProfileBySellerId) {
		this.userProfileBySellerId = userProfileBySellerId;
	}

	@Column(name = "STATUS", nullable = false, length = 60)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "COMMENT")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "negotiation")
//	public Set getInboxOutboxes() {
//		return this.inboxOutboxes;
//	}
//
//	public void setInboxOutboxes(Set inboxOutboxes) {
//		this.inboxOutboxes = inboxOutboxes;
//	}

}
