package com.ffp.data;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "crm")
public class Notification implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String toEmailList;
	private String cclist;
	private String bcclist;
	private Date sentdttm;
	private String subject;
	private String orderId;

	public Notification() {
	}

	public Notification(String toEmailList, Date sentdttm, String subject, String orderId) {
		this.toEmailList = toEmailList;
		this.sentdttm = sentdttm;
		this.subject = subject;
		this.orderId = orderId;
	}

	public Notification(String toEmailList, String cclist, String bcclist, Date sentdttm, String subject,
			String orderId) {
		this.toEmailList = toEmailList;
		this.cclist = cclist;
		this.bcclist = bcclist;
		this.sentdttm = sentdttm;
		this.subject = subject;
		this.orderId = orderId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TO_EMAIL_LIST", nullable = false)
	public String getToEmailList() {
		return this.toEmailList;
	}

	public void setToEmailList(String toEmailList) {
		this.toEmailList = toEmailList;
	}

	@Column(name = "CCLIST")
	public String getCclist() {
		return this.cclist;
	}

	public void setCclist(String cclist) {
		this.cclist = cclist;
	}

	@Column(name = "BCCLIST")
	public String getBcclist() {
		return this.bcclist;
	}

	public void setBcclist(String bcclist) {
		this.bcclist = bcclist;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SENTDTTM", nullable = false, length = 19)
	public Date getSentdttm() {
		return this.sentdttm;
	}

	public void setSentdttm(Date sentdttm) {
		this.sentdttm = sentdttm;
	}

	@Column(name = "SUBJECT", nullable = false)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

}
