package com.ffp.data;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "crm")
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String orderId;
	private String productId;
	private String sellerId;
	private String buyerId;
	private String quantity;
	private String measurement;
	private Date orderDate;
	private int acceptedBySeller;
	private int notificationSentSeller;
	private int notificationSentBuyer;

	public Order() {
	}

	public Order(String orderId, String productId, String sellerId, String buyerId, String quantity, String measurement,
			Date orderDate, int acceptedBySeller, int notificationSentSeller, int notificationSentBuyer) {
		this.orderId = orderId;
		this.productId = productId;
		this.sellerId = sellerId;
		this.buyerId = buyerId;
		this.quantity = quantity;
		this.measurement = measurement;
		this.orderDate = orderDate;
		this.acceptedBySeller = acceptedBySeller;
		this.notificationSentSeller = notificationSentSeller;
		this.notificationSentBuyer = notificationSentBuyer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ORDER_ID", nullable = false)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "PRODUCT_ID", nullable = false)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "SELLER_ID", nullable = false)
	public String getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	@Column(name = "BUYER_ID", nullable = false)
	public String getBuyerId() {
		return this.buyerId;
	}

	public void setBuyerId(String buyerId) {
		this.buyerId = buyerId;
	}

	@Column(name = "QUANTITY", nullable = false)
	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	@Column(name = "MEASUREMENT", nullable = false)
	public String getMeasurement() {
		return this.measurement;
	}

	public void setMeasurement(String measurement) {
		this.measurement = measurement;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ORDER_DATE", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "ACCEPTED_BY_SELLER", nullable = false)
	public int getAcceptedBySeller() {
		return this.acceptedBySeller;
	}

	public void setAcceptedBySeller(int acceptedBySeller) {
		this.acceptedBySeller = acceptedBySeller;
	}

	@Column(name = "NOTIFICATION_SENT_SELLER", nullable = false)
	public int getNotificationSentSeller() {
		return this.notificationSentSeller;
	}

	public void setNotificationSentSeller(int notificationSentSeller) {
		this.notificationSentSeller = notificationSentSeller;
	}

	@Column(name = "NOTIFICATION_SENT_BUYER", nullable = false)
	public int getNotificationSentBuyer() {
		return this.notificationSentBuyer;
	}

	public void setNotificationSentBuyer(int notificationSentBuyer) {
		this.notificationSentBuyer = notificationSentBuyer;
	}

}
