package com.ffp.data;
// Generated Jul 28, 2017 5:52:41 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductVariety generated by hbm2java
 */
@Entity
@Table(name = "product_variety", catalog = "crm")
public class ProductVariety implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String product;
	private String variety;
	private String type;
	private String productDescription;

	public ProductVariety() {
	}

	public ProductVariety(String product, String variety, String type) {
		this.product = product;
		this.variety = variety;
		this.type = type;
	}

	public ProductVariety(String product, String variety, String type, String productDescription) {
		this.product = product;
		this.variety = variety;
		this.type = type;
		this.productDescription = productDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "PRODUCT", nullable = false)
	public String getProduct() {
		return this.product;
	}

	public void setProduct(String product) {
		this.product = product;
	}

	@Column(name = "VARIETY", nullable = false)
	public String getVariety() {
		return this.variety;
	}

	public void setVariety(String variety) {
		this.variety = variety;
	}

	@Column(name = "TYPE", nullable = false, length = 60)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "PRODUCT_DESCRIPTION")
	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

}
