package com.ffp.data;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "crm")
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String type;
	private String imagePath;
	private String sellerId;
	private String productInfo;
	private String productDesc;
	private String quantityAvailable;
	private String price;
	private String measurement;
	private int available;
	private int isActive;

	public Product() {
	}

	public Product(String name, String sellerId, String quantityAvailable, String price, String measurement,
			int available, int isActive) {
		this.name = name;
		this.sellerId = sellerId;
		this.quantityAvailable = quantityAvailable;
		this.price = price;
		this.measurement = measurement;
		this.available = available;
		this.isActive = isActive;
	}

	public Product(String name, String type, String imagePath, String sellerId, String productInfo, String productDesc,
			String quantityAvailable, String price, String measurement, int available, int isActive) {
		this.name = name;
		this.type = type;
		this.imagePath = imagePath;
		this.sellerId = sellerId;
		this.productInfo = productInfo;
		this.productDesc = productDesc;
		this.quantityAvailable = quantityAvailable;
		this.price = price;
		this.measurement = measurement;
		this.available = available;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE")
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "IMAGE_PATH")
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "SELLER_ID", nullable = false, length = 40)
	public String getSellerId() {
		return this.sellerId;
	}

	public void setSellerId(String sellerId) {
		this.sellerId = sellerId;
	}

	@Column(name = "PRODUCT_INFO")
	public String getProductInfo() {
		return this.productInfo;
	}

	public void setProductInfo(String productInfo) {
		this.productInfo = productInfo;
	}

	@Column(name = "PRODUCT_DESC")
	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	@Column(name = "QUANTITY_AVAILABLE", nullable = false)
	public String getQuantityAvailable() {
		return this.quantityAvailable;
	}

	public void setQuantityAvailable(String quantityAvailable) {
		this.quantityAvailable = quantityAvailable;
	}

	@Column(name = "PRICE", nullable = false)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "MEASUREMENT", nullable = false)
	public String getMeasurement() {
		return this.measurement;
	}

	public void setMeasurement(String measurement) {
		this.measurement = measurement;
	}

	@Column(name = "AVAILABLE", nullable = false)
	public int getAvailable() {
		return this.available;
	}

	public void setAvailable(int available) {
		this.available = available;
	}

	@Column(name = "IS_ACTIVE", nullable = false)
	public int getIsActive() {
		return this.isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

}
