package com.ffp.data;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "crm")
public class UserProfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String userName;
	private String password;
	private String userType;
	private String firstName;
	private String lastName;
	private String emailId;
	private String phoneNumber;
	private String secondaryContact;
	private String address;
	private int aprroved;
	private int approvedBy;
	private Date approvedDate;
//	private Set ordersForBuyerId = new HashSet(0);
//	private Set products = new HashSet(0);
//	private Set ordersForSellerId = new HashSet(0);

	public UserProfile() {
	}

	public UserProfile(String userName, String password, String userType, String firstName, String lastName,
			String emailId, String phoneNumber, int aprroved, int approvedBy, Date approvedDate) {
		this.userName = userName;
		this.password = password;
		this.userType = userType;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.phoneNumber = phoneNumber;
		this.aprroved = aprroved;
		this.approvedBy = approvedBy;
		this.approvedDate = approvedDate;
	}

	public UserProfile(String userName, String password, String userType, String firstName, String lastName,
			String emailId, String phoneNumber, String secondaryContact, String address, int aprroved, int approvedBy,
			Date approvedDate) {
//			, Set ordersForBuyerId, Set products, Set ordersForSellerId) {
		this.userName = userName;
		this.password = password;
		this.userType = userType;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.phoneNumber = phoneNumber;
		this.secondaryContact = secondaryContact;
		this.address = address;
		this.aprroved = aprroved;
		this.approvedBy = approvedBy;
		this.approvedDate = approvedDate;
//		this.ordersForBuyerId = ordersForBuyerId;
//		this.products = products;
//		this.ordersForSellerId = ordersForSellerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USER_NAME", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "USER_TYPE", nullable = false, length = 45)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL_ID", nullable = false, length = 100)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "PHONE_NUMBER", nullable = false, length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "SECONDARY_CONTACT", length = 45)
	public String getSecondaryContact() {
		return this.secondaryContact;
	}

	public void setSecondaryContact(String secondaryContact) {
		this.secondaryContact = secondaryContact;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "APRROVED", nullable = false)
	public int getAprroved() {
		return this.aprroved;
	}

	public void setAprroved(int aprroved) {
		this.aprroved = aprroved;
	}

	@Column(name = "APPROVED_BY", nullable = false)
	public int getApprovedBy() {
		return this.approvedBy;
	}

	public void setApprovedBy(int approvedBy) {
		this.approvedBy = approvedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APPROVED_DATE", nullable = false, length = 19)
	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfileByBuyerId")
//	public Set getOrdersForBuyerId() {
//		return this.ordersForBuyerId;
//	}
//
//	public void setOrdersForBuyerId(Set ordersForBuyerId) {
//		this.ordersForBuyerId = ordersForBuyerId;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
//	public Set getProducts() {
//		return this.products;
//	}
//
//	public void setProducts(Set products) {
//		this.products = products;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfileBySellerId")
//	public Set getOrdersForSellerId() {
//		return this.ordersForSellerId;
//	}
//
//	public void setOrdersForSellerId(Set ordersForSellerId) {
//		this.ordersForSellerId = ordersForSellerId;
//	}

}
