package com.ffp.data;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "crm")
public class UserProfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String userName;
	private String password;
	private String userType;
	private String companyName;
	private String firstName;
	private String lastName;
	private String emailId;
	private String phoneNumber;
	private String secondaryContact;
	private String address;
	private String city;
	private String country;
	private int aprroved;
	private String primaryActivity;
	private String countryOfOperation;
	private String operationSince;
	private String typeFruit;
	private String typeFruitVariety;
	private String annualOpQuantity;
	private String weightIn;
	private String currentOpCountry;
	private Date dob;
	private String secretQuestion;
	private String secretAnswer;
//	private Set aprrovals = new HashSet(0);
//	private Set ordersForBuyerId = new HashSet(0);
//	private Set products = new HashSet(0);
//	private Set demands = new HashSet(0);
//	private Set ordersForSellerId = new HashSet(0);

	public UserProfile() {
	}

	public UserProfile(String userName, String password, String userType, String companyName, String firstName,
			String lastName, String emailId, String phoneNumber, String address, String city, String country,
			int aprroved, Date dob, String secretQuestion, String secretAnswer) {
		this.userName = userName;
		this.password = password;
		this.userType = userType;
		this.companyName = companyName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.phoneNumber = phoneNumber;
		this.address = address;
		this.city = city;
		this.country = country;
		this.aprroved = aprroved;
		this.dob = dob;
		this.secretQuestion = secretQuestion;
		this.secretAnswer = secretAnswer;
	}

	public UserProfile(String userName, String password, String userType, String companyName, String firstName,
			String lastName, String emailId, String phoneNumber, String secondaryContact, String address, String city,
			String country, int aprroved, String primaryActivity, String countryOfOperation, String operationSince,
			String typeFruit, String typeFruitVariety, String annualOpQuantity, String weightIn,
			String currentOpCountry, Date dob, String secretQuestion, String secretAnswer) {
		
//	, Set aprrovals,
//			Set ordersForBuyerId, Set products, Set demands, Set ordersForSellerId) {
		this.userName = userName;
		this.password = password;
		this.userType = userType;
		this.companyName = companyName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.phoneNumber = phoneNumber;
		this.secondaryContact = secondaryContact;
		this.address = address;
		this.city = city;
		this.country = country;
		this.aprroved = aprroved;
		this.primaryActivity = primaryActivity;
		this.countryOfOperation = countryOfOperation;
		this.operationSince = operationSince;
		this.typeFruit = typeFruit;
		this.typeFruitVariety = typeFruitVariety;
		this.annualOpQuantity = annualOpQuantity;
		this.weightIn = weightIn;
		this.currentOpCountry = currentOpCountry;
		this.dob = dob;
		this.secretQuestion = secretQuestion;
		this.secretAnswer = secretAnswer;
//		this.aprrovals = aprrovals;
//		this.ordersForBuyerId = ordersForBuyerId;
//		this.products = products;
//		this.demands = demands;
//		this.ordersForSellerId = ordersForSellerId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USER_NAME", nullable = false, length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PASSWORD", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "USER_TYPE", nullable = false, length = 45)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "COMPANY_NAME", nullable = false)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "EMAIL_ID", nullable = false, length = 100)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "PHONE_NUMBER", nullable = false, length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "SECONDARY_CONTACT", length = 45)
	public String getSecondaryContact() {
		return this.secondaryContact;
	}

	public void setSecondaryContact(String secondaryContact) {
		this.secondaryContact = secondaryContact;
	}

	@Column(name = "ADDRESS", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "CITY", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "COUNTRY", nullable = false, length = 60)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "APRROVED", nullable = false)
	public int getAprroved() {
		return this.aprroved;
	}

	public void setAprroved(int aprroved) {
		this.aprroved = aprroved;
	}

	@Column(name = "PRIMARY_ACTIVITY")
	public String getPrimaryActivity() {
		return this.primaryActivity;
	}

	public void setPrimaryActivity(String primaryActivity) {
		this.primaryActivity = primaryActivity;
	}

	@Column(name = "COUNTRY_OF_OPERATION", length = 300)
	public String getCountryOfOperation() {
		return this.countryOfOperation;
	}

	public void setCountryOfOperation(String countryOfOperation) {
		this.countryOfOperation = countryOfOperation;
	}

	@Column(name = "OPERATION_SINCE", length = 45)
	public String getOperationSince() {
		return this.operationSince;
	}

	public void setOperationSince(String operationSince) {
		this.operationSince = operationSince;
	}

	@Column(name = "TYPE_FRUIT", length = 45)
	public String getTypeFruit() {
		return this.typeFruit;
	}

	public void setTypeFruit(String typeFruit) {
		this.typeFruit = typeFruit;
	}

	@Column(name = "TYPE_FRUIT_VARIETY", length = 300)
	public String getTypeFruitVariety() {
		return this.typeFruitVariety;
	}

	public void setTypeFruitVariety(String typeFruitVariety) {
		this.typeFruitVariety = typeFruitVariety;
	}

	@Column(name = "ANNUAL_OP_QUANTITY", length = 45)
	public String getAnnualOpQuantity() {
		return this.annualOpQuantity;
	}

	public void setAnnualOpQuantity(String annualOpQuantity) {
		this.annualOpQuantity = annualOpQuantity;
	}

	@Column(name = "WEIGHT_IN", length = 45)
	public String getWeightIn() {
		return this.weightIn;
	}

	public void setWeightIn(String weightIn) {
		this.weightIn = weightIn;
	}

	@Column(name = "CURRENT_OP_COUNTRY", length = 60)
	public String getCurrentOpCountry() {
		return this.currentOpCountry;
	}

	public void setCurrentOpCountry(String currentOpCountry) {
		this.currentOpCountry = currentOpCountry;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", nullable = false, length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "SECRET_QUESTION", nullable = false)
	public String getSecretQuestion() {
		return this.secretQuestion;
	}

	public void setSecretQuestion(String secretQuestion) {
		this.secretQuestion = secretQuestion;
	}

	@Column(name = "SECRET_ANSWER", nullable = false, length = 60)
	public String getSecretAnswer() {
		return this.secretAnswer;
	}

	public void setSecretAnswer(String secretAnswer) {
		this.secretAnswer = secretAnswer;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
//	public Set getAprrovals() {
//		return this.aprrovals;
//	}
//
//	public void setAprrovals(Set aprrovals) {
//		this.aprrovals = aprrovals;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfileByBuyerId")
//	public Set getOrdersForBuyerId() {
//		return this.ordersForBuyerId;
//	}
//
//	public void setOrdersForBuyerId(Set ordersForBuyerId) {
//		this.ordersForBuyerId = ordersForBuyerId;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
//	public Set getProducts() {
//		return this.products;
//	}
//
//	public void setProducts(Set products) {
//		this.products = products;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfile")
//	public Set getDemands() {
//		return this.demands;
//	}
//
//	public void setDemands(Set demands) {
//		this.demands = demands;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userProfileBySellerId")
//	public Set getOrdersForSellerId() {
//		return this.ordersForSellerId;
//	}
//
//	public void setOrdersForSellerId(Set ordersForSellerId) {
//		this.ordersForSellerId = ordersForSellerId;
//	}

}

